[package]
name = "piet-dx12"
version = "0.1.0"
authors = ["bhmerchant@gmail.com <bhmerchant@gmail.com>"]
edition = "2018"

[dependencies]
winapi = { version = "0.3.*", features = ["winuser", "libloaderapi", "shellscalingapi", "d3d12sdklayers"] }
wio = "0.2.*"
d3d12 = "0.1.*"